---
# vim: set ft=ansible :
# Tasks for CentOS

- name: install yum packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - java-1.8.0-openjdk-devel
    - git

- name: download maven
  get_url:
    url: http://www-eu.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/{{ maven_archive }}
    dest: /vagrant/{{ maven_archive }}
    checksum: sha512:{{ maven_archive_sha512 }}

- name: install maven
  unarchive: src=/vagrant/{{ maven_archive }} dest=/opt copy=no

- name: set up env
  shell: echo {{ item }} >> .bashrc
  args:
    chdir:   /home/vagrant/
    creates: .bashrc.done
  with_items:
    - alias ls=\'ls -F --color=auto\'
    - alias ll=\'ls -l\'
    - alias la=\'ls -A\'
    - export JAVA_HOME=/etc/alternatives/java_sdk
    - export MAVEN_HOME=/opt/{{ maven }}
    - export PATH=\$MAVEN_HOME/bin:\$PATH

- name: put "set up env" done file
  shell: touch .bashrc.done
  args:
    chdir:   /home/vagrant/
    creates: .bashrc.done
