---
# Tasks for CentOS

- name: install yum packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - java-1.8.0-openjdk-devel

- name: download maven
  get_url:
    url: http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/{{ maven_archive }}
    dest: /vagrant/{{ maven_archive }}
    checksum: md5:{{ maven_archive_md5}}

- name: install maven
  unarchive: src=/vagrant/{{ maven_archive }} dest=/opt copy=no

- name: set up env
  shell: echo {{ item }} >> /home/vagrant/.bashrc
  with_items:
    - alias ls=\'ls -F --color=auto\'
    - alias ll=\'ls -l\'
    - alias la=\'ls -A\'
    - export JAVA_HOME=/etc/alternatives/java_sdk
    - export MAVEN_HOME=/opt/{{ maven }}
    - export PATH=\$MAVEN_HOME/bin:\$PATH
