---
# vim: set ft=ansible :
# CentOS 7 Playbook

- hosts: centos7
  gather_facts: false
  become: true
  tasks:
    - include_vars: ../ansible/vars.yml
    - include:      ../ansible/tasks-centos.yml
